### ISSUE TITLE
Crazy things you can do with the F# ternary operator

### ISSUE THREAD

**Issue by Alxandr** [Alxandr/alxandr.me#7]

**Comment by Alxandr** [comment]
Test comment.

**Comment by Alxandr** [comment]
Second comment. Very different. Good stuffs.

```js
const isSmart = (self) => {
  // Much code - so good.
  if (self === 'smart') {
    return true; // duh
  }

  return false;
};
```

**Comment by tipsy** [comment]
Test

**Comment by tychota** [comment]
It is really awesome. Are this comment plugin under MIT, like the rest of the site ?

**Comment by Alxandr** [comment]
Yes. By all means, steal anything you'd like from this page. That being said, things haven't been made very generally, so a lot of the things are dependent on other things. I sort of just got to the "it's working" stage, and stopped working on it. It'll likely be improved slowly over time, and I'd like to split out the comments (cause I don't like how they work currently), but it's too much hassle when it's currently (for the most part) working 😛.

**Comment by signalwerk** [comment]
agree the comment tool is so cool!
